name: Deploy to Heroku
on: ["push"]
env:
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repository
        uses: actions/checkout@v3
      - name: DeployHeroku with github secrets
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.heroku_api_key }}
          heroku_app_name: where-2-park
          heroku_email: ${{ secrets.heroku_email }}
          branch: ${{ github.ref_name }}
        env:
          HD_SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          HD_SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          HD_SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}